### ISSUE TITLE
Ruby 2.2.0 + bcrypt + ActiveRecord + YAML → BCrypt::Errors::InvalidSalt

### ISSUE THREAD

**Issue by be9** [codahale/bcrypt-ruby#106]
There's a problem with dumping AR records using bcrypt under Ruby 2.2.0. I isolated the problem here: https://gist.github.com/be9/c549ff6469d5627aa900

The [script](https://gist.github.com/be9/c549ff6469d5627aa900#comment-1368187) shows how to run the thing and what happens. Everything works perfectly under Ruby 2.1.5, but under Ruby 2.2.0 exception gets raised.

**Comment by recurser** [comment]
:+1:

**Comment by be9** [comment]
Updated the gist with even more minimal test: https://gist.github.com/be9/c549ff6469d5627aa900#file-minitest-rb

```ruby
require 'rubygems'
require 'bundler/setup'
require 'bcrypt'
require 'psych'

# This raises BCrypt::Errors::InvalidSalt under Ruby 2.2.0 and bcrypt 3.1.9
BCrypt::Password.create("my password").to_yaml
```

**Comment by ugoa** [comment]
:+1:

**Comment by svoop** [comment]
Thanks for the fix, @mattwildig, hope it will be adopted and published soon. (With omniauth-identity, this issue causes quite some headache, at least I couldn't bundle the fixed version from mattwildig/bcrypt-ruby and had to manually patch the line in the deployed gem.)

**Comment by jmccartie** [comment]
:+1:

**Comment by rmarescu** [comment]
:+1: 

A bit of a blocker for anybody who uses `bcrypt` and wants to upgrade to Ruby 2.2.0

**Comment by svoop** [comment]
Thanks a bunch, @tjschuck !

**Comment by rmarescu** [comment]
Awesome, thanks!

**Comment by yukas** [comment]
Hey, guys

Since Rails 3.2 is no longer maintained we can't bump bcrypt-ruby version to 3.1 in Rails 3.2. So the problem still persists.

Can we release bcrypt-ruby 3.0.x with this bug fixed?

I already made the fix [here](https://github.com/yukas/bcrypt-ruby/tree/apply-issue-106-fix-to-3-0-version), but there is no bcrypt-ruby 3.0.x branch to make a PR in :(

Can someone help me with releasing 3.0.x version with this bug fixed?

**Comment by yukas** [comment]
@tjschuck can you help me out here?

**Comment by tjschuck** [comment]
@yukas Rails 3.2 is no longer supported even for security updates, so you should either a.) upgrade to a more recent version of Rails, or b.) already be maintaining your own fork of 3.2 so that you can patch it with fixes like the one you mentioned.
