### ISSUE TITLE
Error: You don't have bcrypt-ruby installed in your application.

### ISSUE THREAD

**Issue by Padmahas** [codahale/bcrypt-ruby#125]
Hello codahale and the community,
I'm using rails 4.2.4, ruby 2.2.3 p173 and Ubuntu server 15.04.
I've surely installed bcrypt by adding ` gem 'bcrypt', '3.1.10'` to my gemfile and executing `bundle install` had installed bcrypt successfully. But while following [Michael Hartl's](https://www.railstutorial.org/book/modeling_users#sec-a_hashed_password) tutorial, I also `added has_secure_password`to User model. And in `rails console`, while adding new user, I get the error,

`You don't have bcrypt-ruby installed in your application. Please add it to your Gemfile and run bundle install`

Another error both in browser and in rails console is
`Gem::LoadError: bcrypt-ruby is not part of the bundle. Add it to Gemfile`

Some extra information shown in rails console is
`from /usr/local/lib/ruby/gems/2.2.0/gems/budler-1.10.6/lib/bundler/rubygems_integration.rb:292:in 'block in replace_gem'`

If I completely uninstall bcrypt and give bcrypt-ruby and install it, a new error is shown as
`can't activate bcrypt-ruby (~> 3.0.0), already activated bcrypt-ruby-3.1.5. Make sure all dependencies are added to Gemfile.`
Restarting server (even whole VM) is not working. 
Can anyone please tell me how to over come this error?

Thank you.

**Comment by Padmahas** [comment]
OK, by uninstalling all versions of bcrypt gem and installing bcrypt-ruby of 3.0.0 version by specifying inside gemfile solved the problem. However the bundle install is showing post installation message that `bcrypt-ruby` has changed to `bcrypt` and I have to replace bcrypt-ruby with bcrypt in gemfile. Definitely I'm going to get error if I do this. Hence how can I avoid error by keeping `bcrypt` in the gemfile ?

Thank you

**Comment by tjschuck** [comment]
The error message

> You don't have bcrypt-ruby installed in your application. Please add it to your Gemfile and run bundle install

is coming from Rails.

However, since https://github.com/rails/rails/pull/14149, the gem name in Rails (including that error message) has been updated from bcrypt-ruby to bcrypt, so your error message saying "bcrypt-ruby" implies that you're using a too old version of Rails (specifically, ActiveModel).

That change has been [backported as far back as 4-0-stable](https://github.com/rails/rails/pull/14210) to avoid this case.  It's been included on 4.2 since 4.2.1.

Based on your error message, it seems like you're not actually using 4.2.4 (or else the error message wouldn't say "bcrypt-ruby").  You just need to upgrade your Rails version.

**Comment by Padmahas** [comment]
I agree with you @tjschuck , but I think the problem is because I'm customizing the [selfstarter project](https://github.com/lockitron/selfstarter) which says the app is `updated for rails 4 and ruby 2` and also had old version of gems specified in its Gemfile. But when I tried to run this project as it is, on my rails 4.2.4 and ruby 2.2.3 (yes I'm 100% sure of the version), I came across several gem version problems and some times I even edited Gemfile.**lock** including rails version.

Hence I think the message is about other dependencies that bcrypt depends on. And may be it is showing the message no matter what the rails version is. Because when I left the choice of selecting the version to rails itself by not mentioning the version in gemfile, it installed 3.1.10 by default and when the app is restarted, it specifically asked for `bcrypt-ruby` to be mentioned in gemfile (as I've stated in my first post).
Here is the output of `gem list`. You may find depending on what other gem it asked me to install bcrypt-ruby.

actionmailer (4.2.4, 4.0.0)
actionpack (4.2.4, 4.0.0)
actionview (4.2.4)
activejob (4.2.4)
activemodel (4.2.4, 4.0.0)
activerecord (4.2.4, 4.0.0)
activerecord-deprecated_finders (1.0.3)
activesupport (4.2.4, 4.0.0)
addressable (2.3.8)
amazon_flex_pay (0.10.0)
arel (6.0.3, 4.0.1)
atomic (1.1.14)
autoprefixer-rails (6.0.3)
bcrypt (3.1.10)
bcrypt-ruby (3.0.0)
bigdecimal (1.2.6)
binding_of_caller (0.7.2)
bootstrap-sass (3.3.5.1)
builder (3.2.2, 3.1.4)
bundler (1.10.6)
byebug (6.0.2)
coderay (1.1.0)
coffee-rails (4.1.0, 4.0.1)
coffee-script (2.4.1, 2.2.0)
coffee-script-source (1.9.1.1, 1.6.3)
daemons (1.1.9)
debug_inspector (0.0.2)
diff-lcs (1.2.5)
erubis (2.7.0)
eventmachine (1.0.8)
execjs (2.6.0, 2.0.2)
faraday (0.9.2)
globalid (0.3.6)
hashie (3.4.2)
hike (1.2.3)
i18n (0.7.0, 0.6.5)
io-console (0.4.3)
jbuilder (2.3.1)
jquery-rails (4.0.5, 3.0.4)
jquery-ui-rails (4.1.0)
json (1.8.3, 1.8.1)
jwt (1.5.1)
loofah (2.0.3)
mail (2.6.3, 2.5.4)
method_source (0.8.2)
mime-types (2.6.2, 1.25)
mini_portile (0.6.2)
minitest (5.8.1, 5.4.3, 4.7.5)
multi_json (1.11.2, 1.8.2)
multi_xml (0.5.5)
multipart-post (2.0.0)
nokogiri (1.6.6.2)
oauth (0.4.7)
oauth2 (1.0.0)
omniauth (1.2.2)
omniauth-facebook (2.0.1)
omniauth-google-oauth2 (0.2.8)
omniauth-oauth (1.1.0)
omniauth-oauth2 (1.3.1)
omniauth-twitter (1.2.1)
pg (0.18.3, 0.17.0)
polyglot (0.3.3)
power_assert (0.2.2)
pry (0.9.12.3)
pry-rails (0.3.2)
psych (2.0.8)
rack (1.6.4, 1.5.2)
rack-test (0.6.3, 0.6.2)
rails (4.2.4, 4.0.0)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.2)
rails_12factor (0.0.2)
rails_config (0.3.3)
rails_serve_static_assets (0.0.1)
rails_stdout_logging (0.0.3)
railties (4.2.4, 4.0.0)
rake (10.4.2, 10.1.0)
rb-readline (0.5.3)
rdoc (4.2.0)
rest-client (1.6.7)
rspec-core (2.14.7)
rspec-expectations (2.14.4)
rspec-mocks (2.14.4)
rspec-rails (2.14.0)
sass (3.4.18, 3.2.12)
sass-rails (5.0.4, 4.0.1)
sdoc (0.4.1)
shoulda (3.5.0)
shoulda-context (1.1.6)
shoulda-matchers (2.4.0)
slop (3.4.7)
social-share-button (0.1.8)
sprockets (3.3.5, 2.10.0)
sprockets-rails (2.3.3, 2.0.1)
test-unit (3.0.8)
thin (1.6.1)
thor (0.19.1, 0.18.1)
thread_safe (0.3.5, 0.1.3)
tilt (2.0.1, 1.4.1)
treetop (1.4.15)
turbolinks (2.5.3)
tzinfo (1.2.2, 0.3.38)
uglifier (2.7.2, 2.2.1)
web-console (2.2.1)

**And the new thing is, just to get rid of this error, I mentioned `gem 'bcrypt-ruby', '3.0.0'` and as you can see in the gem list, it installed both 3.1.10 and 3.0.0 automatically but using 3.0.0.**
I've used this gem before without any problem in my home. And its clearly the issue with selfstarter's Gemfile.lock and Gemfile.

Anyway thank you for this great gem. It eliminated the password encryption code to be written by each developer.

**Comment by tjschuck** [comment]
So your problem is probably [this line](https://github.com/lockitron/selfstarter/blob/740075f4d3f71b2b87e8ad6c9b04ef7e50eecfcb/Gemfile#L5) in selfstarter -- it's pegged to 4.0.0.

If you wanted to be safe (i.e. stay on 4.0.x, which is all it alleges support for), you could just update this line to be `gem 'rails', '~> 4.0.0'` and run `bundle update rails`.  That should take you up to 4.0.13 as of today, which includes the gem name update.
