### ISSUE TITLE
The same problem

### ISSUE THREAD

**Issue by andim27** [codahale/bcrypt-ruby#126]
win 7 64bit, 
ruby 2.2.3 [x64-mingw32]
rails s 
has error:
![ruby_bcrypt_error](https://cloud.githubusercontent.com/assets/4599713/10951256/2b2eb01e-8345-11e5-92ae-3d4028b1551b.png)
but
irb>require 'bcrypt'
=>true

How to fix?Help!

**Comment by danfstucky** [comment]
I have the same problem.  I hope they plan on fixing this soon.  I need to run ruby 2.2.3 on my environment.

**Comment by tjschuck** [comment]
Version 3.1.11 of the bcrypt gem was just pushed to RubyGems which should fix this issue.

You should now be able to `gem install bcrypt` on Windows with none of the above workarounds.

Thanks!
