### ISSUE TITLE
Is there a built-in way to check salt difficulty from generated hash?

### ISSUE THREAD

**Issue by Qqwy** [codahale/bcrypt-ruby#127]
I know that bcrypt hashes internally store algorithm version information and the salt difficulty. For instance, in: 

    `$2y$14$i5btSOiulHhaPHPbgNUGdObga/GC.AVG/y5HHY1ra7L0C9dpCaw8u`

the `2y` part is the version, and `14` is the difficulty.

I can of course extract them using regular expressions, but is there a built-in way to check these things using bcrypt-ruby right now?

**Comment by tjschuck** [comment]
`cost` and `version`:

```ruby
> BCrypt::Password.new("$2a$04$sZwBgi3z1Xb6fAiCatrpIupsqE7WfwDxlB0LgH8qG2bLpgcsGTC0q").cost
=> 4
> BCrypt::Password.new("$2a$04$sZwBgi3z1Xb6fAiCatrpIupsqE7WfwDxlB0LgH8qG2bLpgcsGTC0q").version
=> "2a"
```
