### ISSUE TITLE
git tags missing

### ISSUE THREAD

**Issue by iGEL** [codahale/bcrypt-ruby#129]
The lastest git tag is for 3.1.6, but on Ruby gems the latest version is 3.1.10. Could you push the missing tags? It simplifies lots of things, including easy code comparison. Thanks :heart:

**Comment by suweller** [comment]
Any news on this?
I also use git tags to compare updates.

It should be possible to make tags for `3.1.7` up to and including `3.1.11`.

**Comment by tjschuck** [comment]
I've just added tags and releases for all versions from 3.1.7 through 3.1.12.  Thanks!
