### ISSUE TITLE
Is :version attribute supposed to work? 

### ISSUE THREAD

**Issue by aspyatkin** [codahale/bcrypt-ruby#130]
Hello!
I have a project which uses bcrypt in both Python and Ruby. By default, [bcrypt from pip](https://pypi.python.org/pypi/bcrypt/2.0.0) creates hashes with `2b` algorithm and this library - with `2a` algorithm.

I've found [here](http://bcrypt-ruby.rubyforge.org/classes/BCrypt/Password.html#M000007) that `BCrypt::Password.create` method accepts `version` parameter, but as far a I've understood from the code, the value of this parameter is not taken into account. I tried setting it to `2b`, `$2b$` and so on, but it doesn't seem to work. Is it true that this library supports different `bcrypt` versions?

**Comment by tjschuck** [comment]
@aspyatkin On the page that you linked to, the `[R]` next to `version` indicates that that's a readable attribute and is not user-settable.

bcrypt-ruby's implementation has not yet been updated to support the `2b` prefix.
