### ISSUE TITLE
bcrypt_pbkdf

### ISSUE THREAD

**Issue by mfazekas** [codahale/bcrypt-ruby#134]
I'm net-ssh maintainer and i'd need bcrypt_pbkdf for reading encrypted Ed25519 keys (https://github.com/net-ssh/net-ssh/pull/228). 
see
http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/lib/libutil/bcrypt_pbkdf.c?rev=1.13&content-type=text/x-cvsweb-markup

My question if you would accept PR implementing it? Or shall i implement it in it's own extension?

**Comment by tjschuck** [comment]
@mfazekas Not likely to be accepted into bcrypt-ruby.  This is more a feature to be added to a PBDKF2 library than a feature to be added to a bcrypt lib.

My suggestion would be either:

1. Write and publish your own bcrypt_pbkdf gem.
2. Try to get this added as a feature to https://github.com/emerose/pbkdf2-ruby (the pbkdf2 gem).  It seemingly takes a `hash_function` option, so you might be able to hook into that.

Good luck!

**Comment by mfazekas** [comment]
Thanks much for the quick answer.
I actually only need ```bcrypt_hash``` as i was able to implement bcrypt_pkpdfon top of that using libsodium (see https://github.com/mfazekas/net-ssh/blob/ed25519-key/lib/net/ssh/authentication/ed25519.rb#L75-L116)

According to http://web.mit.edu/freebsd/head/crypto/openssh/openbsd-compat/bcrypt_pbkdf.c:
> * The bcrypt hash function is derived from the bcrypt password hashing
>  * function with the following modifications:
>  * 1. The input password and salt are preprocessed with SHA512.
>  * 2. The output length is expanded to 256 bits.
>  * 3. Subsequently the magic string to be encrypted is lengthened and modifed
>  *    to "OxychromaticBlowfishSwatDynamite"
>  * 4. The hash function is defined to perform 64 rounds of initial state
>  *    expansion. (More rounds are performed by iterating the hash.)
I assume this is also outside of bcrypt-ruby scope, is it?

In that case i'll do gem for that, i don't think there is anything i could use from pbkdf2, because bcrypt-pbkdf is not a pbkdf2 with bcrypt_hash but there are other variations:
http://www.tedunangst.com/flak/post/bcrypt-pbkdf
