### ISSUE TITLE
difference between bcrypt and bcrypt-ruby gems

### ISSUE THREAD

**Issue by mathieujobin** [codahale/bcrypt-ruby#137]
on master, i see the version got bumped to 3.1.11
last tagged released is Version 3.1.6

bcrypt-ruby has https://rubygems.org/gems/bcrypt-ruby/versions/3.1.5
and bcrypt has 3.1.11

is bcrypt-ruby old deprecated name for the gem ?

bcrypt-ruby seems to require the other, so I wonder, what is the difference including this gem ?

```
+    bcrypt (3.1.11)
+    bcrypt-ruby (3.1.5)
+      bcrypt (>= 3.1.3)
```

**Comment by tjschuck** [comment]
> is bcrypt-ruby old deprecated name for the gem ?

Precisely.  See https://github.com/codahale/bcrypt-ruby/pull/86 for more info.
