### ISSUE TITLE
Release to Rubygems

### ISSUE THREAD

**Issue by yukas** [codahale/bcrypt-ruby#138]
Last released gem version seem to be 3.1.5. Current version is 3.1.11. Someone needs to release all versions to Rubygems.

I can help if needed.

**Comment by tjschuck** [comment]
3.1.5 was the last version under [the `bcrypt-ruby` gem name](https://rubygems.org/gems/bcrypt-ruby).  All subsequent versions were released on Rubygems as [just `bcrypt`](https://rubygems.org/gems/bcrypt).  See https://github.com/codahale/bcrypt-ruby/pull/86 for more info.
