### ISSUE TITLE
Support Ruby 2.3 on Windows

### ISSUE THREAD

**Issue by scivola** [codahale/bcrypt-ruby#139]
bcrypt (3.1.11 x86-mingw32) does not contain binary for Ruby 2.3.

Now Windows users can use Ruby 2.3.
http://rubyinstaller.org/downloads/

**Comment by Startouf** [comment]
So basically the same problem as in https://github.com/codahale/bcrypt-ruby/issues/128 ?

**Comment by scivola** [comment]
Yes, it is essentially same.

**Comment by Startouf** [comment]
What should be done to generate a version for Ruby 2.3 (if it is possible). This is the only step that prevents me from migrating to Ruby 2.3.

**Comment by vais** [comment]
@Startouf the following worked for me (with [DevKit](http://rubyinstaller.org/add-ons/devkit/)):
```
C:\Users\Administrator>ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]

C:\Users\Administrator>gem list bcrypt

*** LOCAL GEMS ***

bcrypt (3.1.11 x64-mingw32)

C:\Users\Administrator>gem uninstall bcrypt
Successfully uninstalled bcrypt-3.1.11-x64-mingw32

C:\Users\Administrator>gem list bcrypt

*** LOCAL GEMS ***

C:\Users\Administrator>gem install bcrypt --platform=ruby
Fetching: bcrypt-3.1.11.gem (100%)
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
Successfully installed bcrypt-3.1.11
Parsing documentation for bcrypt-3.1.11
Installing ri documentation for bcrypt-3.1.11
Done installing documentation for bcrypt after 1 seconds
1 gem installed

C:\Users\Administrator>gem list bcrypt

*** LOCAL GEMS ***

bcrypt (3.1.11)
```
:beers:

**Comment by larskanis** [comment]
#117 fixes this issue. Alternatively use the workaround with `gem inst --platform=ruby` .

**Comment by caleuanhopkins** [comment]
Funnily enough, the solution (or work around, whatever you want to call it) seems to fix this issue also: [https://github.com/codahale/bcrypt-ruby/issues/128#issuecomment-190107035](https://github.com/codahale/bcrypt-ruby/issues/128#issuecomment-190107035)

**Comment by sorelyss** [comment]
It works!!! thanks 👍

**Comment by amreos** [comment]
Dear @vais 
Thank you 
this worked for ruby 2.3 32bit version on x64 win 7 if that make any sense
i had to delete any other bcrypt folder in this bath
C:\Ruby23\lib\ruby\gems\2.3.0\gems
thanks again

**Comment by jostster** [comment]
This there a perm fix for this inside the Gemfile? I hate having to install new gems with `bundle install` then uninstall bcrypt manually then manually reinstall it with the platform=ruby.

**Comment by karensg** [comment]
This would be really great!

**Comment by enneid** [comment]
Is it this problem will be perm fixed in any time? or we have to wait for ruby 2.4?

**Comment by bchellingworth** [comment]
Is this issue ever going to get a perm fix, the workaround is painful everytime.

**Comment by sdik** [comment]
gem install bcrypt --platform=ruby
resolveu..

**Comment by mSafdarAli** [comment]
@vais thank you so much. it solved my problem. :+1:

**Comment by johnnyshields** [comment]
This is a dupe of #149 and can be closed (we only need one ticket for it)

**Comment by tjschuck** [comment]
I have just pushed version 3.1.12.rc1 to RubyGems.org which should solve this problem.

Can someone please confirm that `gem install bcrypt --prerelease` now works on Fedora 28?  If so, I'll push out the final version.

**Comment by tjschuck** [comment]
Version 3.1.12 of the bcrypt gem, which should fix this issue, was just pushed to RubyGems.

You should now be able to `gem install bcrypt` on Windows with none of the above workarounds.

Thanks, everyone!
