### ISSUE TITLE
Rails console does't start if gem 'bcrypt','~>3.1.11' is on gemfile

### ISSUE THREAD

**Issue by DiegoRojasV** [codahale/bcrypt-ruby#143]
After adding gem 'bcrypt','~>3.1.11' to my gemfile and run bundle install. I can't start the rails console, it's showing me the following error:

Your bundle is locked to bcrypt (3.1.11), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of bcrypt (3.1.11) has removed it. You'll need to update your bundle to a different version of bcrypt (3.1.11) that hasn't been removed in order to install.
Run `bundle install` to install missing gems.

After that I've tried to run bundle install and bundle update but still getting the same error. The error only is fixed when I remove the line gem 'bcrypt','~>3.1.11' from the gemfile.

Ruby -v: 2.3.1 Rails -v:5.0.0.1

**Comment by haroruhomer** [comment]
Refer to #142 solution

**Comment by tjschuck** [comment]
What OS are you on?  #142 really should only apply to Windows.

What sources are you using in your Gemfile?  Do something like `grep source Gemfile` — do you only have a line like `source 'https://rubygems.org'`?  Based on the error, you might be referencing a gem source that doesn't have that version of bcrypt on it.  [Rubygems definitely does](https://rubygems.org/gems/bcrypt/versions/3.1.11).

**Comment by tjschuck** [comment]
Anyway, this issue is 2 months old — I'm assuming you figured out your issue.  If you haven't, please comment and I'll reopen.  If you have and you remember what your solution was, don't hesitate to add it here for anyone that searches for this error in the future!
