### ISSUE TITLE
I have this error in windows 10 with ruby 2.3.3

### ISSUE THREAD

**Issue by carlos147** [codahale/bcrypt-ruby#146]
LoadError in Devise::RegistrationsController#create
cannot load such file -- bcrypt_ext

      def require(file)
        result = false
        load_dependency(file) { result = super }
        result
      end
    end

**Comment by tjschuck** [comment]
Did you successfully install the bcrypt gem?  What does `gem list bcrypt` tell you?

**Comment by haroruhomer** [comment]
Look if #142 solution works for you

**Comment by tjschuck** [comment]
What @haroruhomer linked (using `--platform=ruby` with the DevKit installed) is my best guess to fix it for you as well.  Closing this pending any additional info.

Thanks, @haroruhomer !
