### ISSUE TITLE
BCrypt::Engine salt changes on saving to database

### ISSUE THREAD

**Issue by prasanthkrajan** [codahale/bcrypt-ruby#151]
I'm working on a rails app that stores crypted password and salt in the db. Salt and crypted_password generate fine but the value of salt changes once saved in the db. The login function breaks due to this, as the password is now being checked with an invalid salt thats saved in the db. 

The salt that's generated by BCrypt::Engine and the salt saved in db are totally different. I'm saving the same BCrypt::Engine generated salt in the db and yet the value changes once saved in the db. It was working fine all this while and started breaking today.

Appreciate your help.

**Comment by tjschuck** [comment]
@prasanthkrajan You don't have to generate or store the salt separately.  The salt is a part of the digest that comes out of BCrypt.

For example, consider the following digest:

```ruby
digest = BCrypt::Password.create("secret")
#=> "$2a$10$j5iDrOHz/eD8vTOh81AaXO9AIKW4KISWZsxYx93N8cMUMZL3azBwS"
```

First, the `$`s are delimiters:

* The `2a` prefix just indicates "this is a BCrypt hash".  `1` would indicate MD5, `5` is SHA-256, etc.  With this lib, you'll always get `2a` here.

* The next field, `10`, is the cost.  See how it changes when you change the cost: `BCrypt::Password.create("secret", cost: 11) #=> "$2a$11$s6CbRVWXL8DwNFvYk1wciOZlrv0YrURamQf45pQkRt5m6d0r0AlQS"`

* The last field includes both the salt _and_ the hash itself:

  * The salt is 128 bits, and it's base-64 encoded as 22 characters
  * The hash is 184 bits, and it's base-64 encoded as 31 characters

So in the digest string provided above (`$2a$10$j5iDrOHz/eD8vTOh81AaXO9AIKW4KISWZsxYx93N8cMUMZL3azBwS`), the salt is `j5iDrOHz/eD8vTOh81AaXO` and the hash is `9AIKW4KISWZsxYx93N8cMUMZL3azBwS`.

When BCrypt checks your plaintext password against the digest, it automatically uses the salt that's encoded into the digest — you don't have to specify any additional salt that you've generated and stored yourself:

```ruby
BCrypt::Password.new("$2a$10$j5iDrOHz/eD8vTOh81AaXO9AIKW4KISWZsxYx93N8cMUMZL3azBwS").is_password?("secret")
=> true
```
