### ISSUE TITLE
Error when uninstalling bcrypt

### ISSUE THREAD

**Issue by Morganja95** [codahale/bcrypt-ruby#155]
When typing `gem uninstall bcrypt` into Git Bash it returns this message...

```
ERROR:  While executing gem ... (Gem::DependencyRemovalException)
    Uninstallation aborted due to dependent gem(s)
```

I am trying to get bcrypt to work and this is part of the process I found, yet during this step, I ran into this problem that I can't overcome. Would love some help, thanks!

P.S I already uninstalled bcrypt-ruby.

**Comment by tjschuck** [comment]
Try `gem dependency bcrypt-ruby` to see what gems are currently depending on it.

**Comment by Morganja95** [comment]
`No gems found matching bcrypt-ruby (>= 0)`

That's all it responds with.

**Comment by Morganja95** [comment]
Now when I use this command `gem dependency bcrypt`

This message occurs: 

`Gem bcrypt-3.1.11
  rake-compiler (~> 0.9.2, development)
  rdoc (~> 3.12, development)
  rspec (>= 3, development)`

**Comment by tjschuck** [comment]
What exactly are you trying to do?  You said: 

> I am trying to get bcrypt to work and this is part of the process I found

Uninstalling bcrypt is usually not a good step to using it :)  You already have it installed, so what's the issue?

**Comment by Morganja95** [comment]
well bcrypt isnt working on my rails project and I was trying to reinstall it. I read a few articles saying that would fix the issue.

**Comment by tjschuck** [comment]
@Morganja95 Are you using Bundler to manage your gems (via a Gemfile)?  What does `bundle list bcrypt` report?  What do the `bcrypt` lines in your Gemfile and Gemfile.lock look like?

**Comment by tjschuck** [comment]
And what OS are you on?  Mac, Windows, or some Linux distribution?

**Comment by Morganja95** [comment]
I am using Windows, and `bundle list bcrypt` responds with this: 
`$ bundle list bcrypt
Could not find gem 'bcrypt'.
Did you mean bcrypt?`

**Comment by Morganja95** [comment]
Ah, I reinstalled it and it came up with this message: 
`C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/bcrypt-3.1.11`

**Comment by Morganja95** [comment]
Wow, I don't know how, but it seems to be working now! I'm just running into some more issues though with my login form. Thank you for the help @tjschuck

**Comment by tjschuck** [comment]
@Morganja95 Glad you got it sorted!  Good luck with the rest!
