### ISSUE TITLE
Documentation vs real behaviour

### ISSUE THREAD

**Issue by Olli** [codahale/bcrypt-ruby#156]
` 
BCrypt::Password.valid_hash?(BCrypt::Password.create("test").to_s)
=> 0
`
This 0 should be true ?! :)

Ruby: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux] via rvm

**Comment by tjschuck** [comment]
`0` is true in Ruby.

```ruby
def zero_truth
  if 0
   "okay"
  else
    "bad"
  end
end

zero_truth
# => "okay"
```

Only `false` and `nil` are false in Ruby.  Everything else is true.
