### ISSUE TITLE
gem install bcrypt report error

### ISSUE THREAD

**Issue by clay-f** [codahale/bcrypt-ruby#160]
terminal type `gem install bcrypt` report this problem
gem -v 2.6.13
ruby -v 2.4.2
OS: mac os 10.13

    Building native extensions.  This could take a while...
    ERROR:  Error installing bcrypt:
        ERROR: Failed to build gem native extension.

        current directory: /Users/f/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bcrypt-3.1.11/ext/mri
    /Users/f/.rbenv/versions/2.4.2/bin/ruby -r ./siteconf20171012-28179-161tt34.rb extconf.rb
    creating Makefile

    current directory: /Users/f/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bcrypt-3.1.11/ext/mri
    make "DESTDIR=" clean

    current directory: /Users/f/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bcrypt-3.1.11/ext/mri
    make "DESTDIR="
    compiling bcrypt_ext.c
    compiling crypt.c
    compiling crypt_blowfish.c
    compiling crypt_gensalt.c
    compiling wrapper.c
    linking shared-object bcrypt_ext.bundle

    current directory: /Users/f/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bcrypt-3.1.11/ext/mri
    make "DESTDIR=" install
    make: /usr/local/opt/coreutils/libexec/gnubin/mkdir: No such file or directory
    make: *** [.sitearchdir.time] Error 1

    make install failed, exit code 2

    Gem files will remain installed in /Users/f/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bcrypt-3.1.11 for inspection.
    Results logged to /Users/f/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-16/2.4.0-static/bcrypt-3.1.11/gem_make.out

**Comment by tenderlove** [comment]
Seems like you're missing `mkdir`?

> make: /usr/local/opt/coreutils/libexec/gnubin/mkdir: No such file or directory

I don't think this is a bug in bcrypt-ruby.
