### ISSUE TITLE
Gem is broken on Fedora 28

### ISSUE THREAD

**Issue by frenkel** [codahale/bcrypt-ruby#170]
After upgrading today I cannot use this gem anymore. The cause seems to be fixed in some local patches when installed using the package manager, however, I cannot get it to be used by my Rails projects. Would be great if you could include these fixes in the gem. More info at https://bugzilla.redhat.com/show_bug.cgi?id=1537140
Thanks in advance!

**Comment by frenkel** [comment]
The actual patches are:
https://src.fedoraproject.org/rpms/rubygem-bcrypt/c/9e7a609d2c7e1c698ab15f299094c789b96a4957?branch=master
and
https://src.fedoraproject.org/rpms/rubygem-bcrypt/c/0e1402a54a037fb78e7fd2fea9b3276e44aa9823?branch=master

**Comment by frenkel** [comment]
Ah, this will be fixed by #164

**Comment by duritong** [comment]
Fedora 28 was release 2 days ago and at the moment you can't use bcrypt on it. Can we get that fixed? Thanks!

**Comment by psychoslave** [comment]
Hi, just run through this issue. Nice to see it was already reported. I made a little [hack to circumvent that in the mid time](https://stackoverflow.com/a/50215812/1307778).

**Comment by tjschuck** [comment]
I have just pushed version 3.1.12.rc1 to RubyGems.org which should solve this problem.

Can someone please confirm that `gem install bcrypt --prerelease` now works on Fedora 28?  If so, I'll push out the final version.

**Comment by Ropeney** [comment]
Seems to have fixed it for me—on Fedora 28.

**Comment by tolbier** [comment]
Thank you tjschuck...just following "Rails Tutorial" by Michael Hartl that uses  bcrypt 3.1.11 ; I was stuck with this "BCrypt::Errors::InvalidHash: invalid hash" issue ...and I've found the solution just an hour after you pushed 3.1.12.rc1 ; TNX!
It works!

**Comment by tjschuck** [comment]
Version 3.1.12 of the bcrypt gem, which should fix this issue, was just pushed to RubyGems.

You should now be able to `gem install bcrypt` on Fedora with none of the above workarounds.

Thanks, everyone!

**Comment by frenkel** [comment]
Great, thank you!
