### ISSUE TITLE
FreeBSD 12 compile broken

### ISSUE THREAD

**Issue by courtland** [codahale/bcrypt-ruby#175]
bcrypt fails to build under FreeBSD-12.0-CURRENT. Please refer to pull request #166 and #150.

**Comment by tjschuck** [comment]
Both #166 and #150 are issues with the vendored C library we use to power bcrypt-ruby.  If those patches are accepted upstream, we'll pull the changes downstream into bcrypt-ruby.

Thanks!

**Comment by wafcio** [comment]
FreeBSD 12 was released but there are problem with installing bcrypt which was presented here. Do you have any hints how it can be solved?

**Comment by rihadik** [comment]
The problem is still there.
