### ISSUE TITLE
Compiled Windows binaries do not support Ruby 2.6

### ISSUE THREAD

**Issue by preetpalS** [codahale/bcrypt-ruby#191]
Version 3.1.12 of the gem installs when using [Ruby 2.6](https://github.com/oneclick/rubyinstaller2/releases/tag/RubyInstaller-2.6.0-1) but you encounter a runtime error when trying to load the library. Related to https://github.com/codahale/bcrypt-ruby/issues/173.

**Comment by tjschuck** [comment]
Hi @preetpalS! We've since dropped support for shipping Windows binaries altogether (https://github.com/codahale/bcrypt-ruby/pull/174), but it hasn't been put into a formal release yet.  In the meantime, you can point your Gemfile at the master branch and it should work:

```
gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git'
```

**Comment by richpeck** [comment]
Many thanks, this saved me a lot of time :)
