### ISSUE TITLE
Support of BCrypt version 2b

### ISSUE THREAD

**Issue by antonakospanos** [codahale/bcrypt-ruby#192]
@tjschuck we are using the `bcrypt` gem and we need to upgrade to `2b` hashes.

I found out that the effort is already done and merged into **master** in the context of [PR-182](https://github.com/codahale/bcrypt-ruby/pull/182) and [PR-132](https://github.com/codahale/bcrypt-ruby/pull/132).

The latest version, at the moment, though, is still **version-3.1.12** since May 2018. Could we please tag the latest master so that we can use `2b` hashes?

**Comment by tjschuck** [comment]
@antonakospanos You're right that it hasn't been put into a formal release yet. In the meantime, you can point your Gemfile at the master branch and it should work:

```
gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git'
```

If you don't want to bundle an unbounded master, you can peg it to a SHA as well:

```
gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', ref: "84c8d7b"
```

A formal release is on my list, but I can't promise a date.
