### ISSUE TITLE
Is 3.1.13 a production-ready release?

### ISSUE THREAD

**Issue by mohamedhafez** [codahale/bcrypt-ruby#199]
If it is, it would be great if it got a changelog entry, and was marked as the latest release in the "releases" tab and on RubyGems. If it isn't, it would be great if it was released with a version number that denoted that, like 3.1.13.rc1 or something. 

(Sorry I don't mean to nitpick, just confused about whether I should update to this version or not, especially since it looks like the tests are failing)

**Comment by tenderlove** [comment]
If you would like to send a PR to fix the tests or add a changelog entry, I would appreciate it.

**Comment by Bertg** [comment]
Hi, It does not seem that the test are failing per see, but the CI did...

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

Maybe just trigger a rerun?
