### ISSUE TITLE
Decrypt method in documentation

### ISSUE THREAD

**Issue by steffanllyn-ln** [codahale/bcrypt-ruby#209]
I'm trying to use BCrypt in Ruby2.6.3 to encrypt and decrypt passwords. The encrypt method works fine - for example,

`BCrypt::Password.create('Password1')`
returns $2a$12$MMZRCG9z2Nkhym.aK9jZseK.gYODB5MHjcdIMxIoRDFGch76RTjdm

However, when I try to decrypt this with:
`BCrypt::Password.new('$2a$12$MMZRCG9z2Nkhym.aK9jZseK.gYODB5MHjcdIMxIoRDFGch76RTjdm')`
I get...
$2a$12$MMZRCG9z2Nkhym.aK9jZseK.gYODB5MHjcdIMxIoRDFGch76RTjdm

Am I missing something here?

**Comment by tjschuck** [comment]
You cannot decrypt a bcrypted password.  It is not an encryption method — it's a hashing method, i.e. it is one-way and irreversible.  It's designed to safely store passwords, i.e. once it's hashed, you _can't_ know what the password is.  However, it's deterministic, which is how you can use it to verify passwords, i.e. the same input will cause the same output.  When a user tries to log in, you hash the password they provide again and compare the hashes — if they match, they're the same.  But the plaintext password itself should never be stored (in _any_ way, included reversibly encrypted).

If you want to learn more about password hashing in general and how bcrypt specifically works, you can check out [this video](https://www.youtube.com/watch?v=9u54O6vARK8).  (Yes, that's me speaking.  I'm not trying to self-promote; it's just an explanation that should do a sufficient job explaining the behavior you're seeing.)  You can also Google along the lines of "password hashing" and find a bunch of articles about how it works.

**Comment by steffanllyn-ln** [comment]
Many thanks for clearing up my confusion!
