### ISSUE TITLE
Version 3.1.13 does not show in the changelog

### ISSUE THREAD

**Issue by esposito** [codahale/bcrypt-ruby#211]
There is no entry for version `3.1.13` in the CHANGELOG file, nor is there a description on the releases page for this repository. Could you please add this description? Then I can check whether it's safe to upgrade.

**Comment by filipkis** [comment]
+1

**Comment by filipkis** [comment]
@tenderlove any chance we get the CHANGELOG updated for `3.1.13`?

**Comment by benpratt** [comment]
v3.1.12 is tagged as the latest release but FreeBSD packages are being built off of v3.1.13 which is causing issues with projects based on release.
