### ISSUE TITLE
unknown attribute 'password' for User.

### ISSUE THREAD

**Issue by jusondac** [codahale/bcrypt-ruby#218]
```
class User < ActiveRecord::Base
	attr_accessor :password
	before_save :add_salt_and_hash

	validates :username, presence: true,uniqueness: true
	validates :email, presence: true, uniqueness: true
	validates :password, uniqueness: true, on: :create,length:{ minimum:5 }, confirmation: true
	def add_salt_and_hash
		unless password.blank?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
		end
	end
end
```
meanwhile in other files, i put 
```
class AddSaltHashToUsers < ActiveRecord::Migration[5.2]
  def change
  	add_column :users,:password_salt,:string
  	rename_column :users,:password,:password_hash
  end
end
```
when run, i got this
```
ActiveModel::UnknownAttributeError in UsersController#create
unknown attribute 'password' for User.
```

**Comment by tjschuck** [comment]
Based on what you provided, that error is "correct" in the sense that you don't have an attribute named `password` on your `User` model — in your migration, you're renaming the `password` attribute to `password_hash`, so it's gone.

That said, it doesn't look like you're necessarily using bcrypt-ruby or storing your password information properly.

1. It doesn't appear that you are based on the code you shared so far, but you should _never_ be storing the plaintext password in any way.

2. You do not need to separately store the salt from bcrypt — the cost, salt, and hash are all included in the final digest string provided by bcrypt-ruby.  You only need to store the output of `BCrypt::Password.create(password)`, which is a string that will look something like `$2a$12$K0ByB.6YI2/OYrB4fQOYLe6Tv0datUVf6VZ/2Jzwm879BW5K1cHey`

3. In general, look at [the readme for this repo](https://github.com/codahale/bcrypt-ruby) for usage notes.

4. Based on what you've included here, I highly recommend you just use the [Rails-provided `has_secure_password` functionality](https://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html), which wraps all of this up for you so you don't have to implement it yourself.  It uses bcrypt-ruby under the hood.

All that said, these GitHub issues are intended for discussion about development of this library itself, not usage of it.

For support issues or usage questions like this one that are not issues with bcrypt-ruby itself, and particularly for this sort of help with basic Rails functionality, please post to the rubyonrails-talk mailing list (http://groups.google.com/group/rubyonrails-talk) or somewhere like StackOverflow using the `ruby-on-rails` tag (http://stackoverflow.com/questions/tagged/ruby-on-rails).  You can also drop in to the #rubyonrails channel on irc.freenode.net for realtime help.  You'll be more likely to get a quick and full answer using one of those options.
