### ISSUE TITLE
BCrypt::Errors::InvalidHash: invalid hash

### ISSUE THREAD

**Issue by rajeevkannav** [codahale/bcrypt-ruby#226]
ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

irb(main):001:0> require 'bcrypt'
=> true
irb(main):002:0> my_password = BCrypt::Password.create("my password")
BCrypt::Errors::InvalidHash: invalid hash
	from /home/wm/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bcrypt-3.1.10/lib/bcrypt/password.rb:60:in `initialize'
	from /home/wm/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bcrypt-3.1.10/lib/bcrypt/password.rb:46:in `new'
	from /home/wm/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bcrypt-3.1.10/lib/bcrypt/password.rb:46:in `create'
	from (irb):2
	from /home/wm/.rbenv/versions/2.2.2/bin/irb:11:in `<main>'

System Details 

Ubuntu 20.04 LTS
OpenSSL 1.0.2l  25 May 2017

**Comment by thewalkingtoast** [comment]
I am also seeing this now after upgrading to Pop!_OS 20.04 LTS x86_64.

**Comment by rajeevkannav** [comment]
@thewalkingtoast, it seems is you upgrade bcrypt gem version to `3.1.13` then this issue does not exists. Can you please confirm the same at your end. May be it help in debugging

**Comment by thewalkingtoast** [comment]
@rajeevkannav That did it. Thank you!
