### ISSUE TITLE
Bcrypt v3.1.14 fails on ruby 2.7 with an invalid hash error

### ISSUE THREAD

**Issue by agrare** [codahale/bcrypt-ruby#230]
Found originally with ManageIQ seeding our users table:
```
BCrypt::Errors::InvalidHash: invalid hash
/home/grare/adam/.gems/2.7.0/gems/bcrypt-3.1.14/lib/bcrypt/password.rb:60:in `initialize'
/home/grare/adam/.gems/2.7.0/gems/bcrypt-3.1.14/lib/bcrypt/password.rb:46:in `new'
/home/grare/adam/.gems/2.7.0/gems/bcrypt-3.1.14/lib/bcrypt/password.rb:46:in `create'
/home/grare/adam/.gems/2.7.0/gems/activemodel-5.2.4.3/lib/active_model/secure_password.rb:120:in `password='
<snip>
/home/grare/adam/src/manageiq/manageiq/app/models/user.rb:391:in `block in seed'
/home/grare/adam/src/manageiq/manageiq/app/models/user.rb:381:in `each'
/home/grare/adam/src/manageiq/manageiq/app/models/user.rb:381:in `seed'
```

The specs also fail on v3.1.14 and pass on v3.1.13 which made git bisecting easy, bisected to e1320b0328b54a890be5f8ba7199fb4f59660fd7 as the first bad commit

```
$ ruby --version
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-gnu]
```

**Comment by Fryguy** [comment]
cc @tenderlove

**Comment by tenderlove** [comment]
Looking at that patch, I don't see how it could cause this error.  Is there any way you can make a failing test case for me?

**Comment by agrare** [comment]
Oh sorry wasn't clear enough, these specs actually fail not the MIQ specs

```
adam@desktop:~/bcrypt-ruby$ git checkout e1320b0328b54a890be5f8ba7199fb4f59660fd7
HEAD is now at e1320b0 unlock the gvl when calculating hashes / salts
adam@desktop:~/bcrypt-ruby$ rake
Finished in 0.42566 seconds (files took 0.12199 seconds to load)
35 examples, 15 failures

Failed examples:

rspec ./spec/bcrypt/engine_spec.rb:6 # BCrypt::Engine .calibrate(upper_time_limit_in_ms) a tiny upper time limit provided returns a minimum cost supported by the algorithm
rspec ./spec/bcrypt/engine_spec.rb:14 # The BCrypt engine should calculate the optimal cost factor to fit in a specific time
rspec ./spec/bcrypt/engine_spec.rb:79 # Generating BCrypt hashes should be interoperable with other implementations
rspec ./spec/bcrypt/password_spec.rb:10 # Creating a hashed password should return a BCrypt::Password
rspec ./spec/bcrypt/password_spec.rb:14 # Creating a hashed password should return a valid bcrypt password
rspec ./spec/bcrypt/password_spec.rb:18 # Creating a hashed password should behave normally if the secret is not a string
rspec ./spec/bcrypt/password_spec.rb:24 # Creating a hashed password should tolerate empty string secrets
rspec ./spec/bcrypt/password_spec.rb:43 # Reading a hashed password the cost should be set to the default if nil
rspec ./spec/bcrypt/password_spec.rb:47 # Reading a hashed password the cost should be set to the default if empty hash
rspec ./spec/bcrypt/password_spec.rb:51 # Reading a hashed password the cost should be set to the passed value if provided
rspec ./spec/bcrypt/password_spec.rb:55 # Reading a hashed password the cost should be set to the global value if set
rspec ./spec/bcrypt/password_spec.rb:62 # Reading a hashed password the cost should be set to an overridden constant for backwards compatibility
rspec ./spec/bcrypt/password_spec.rb:99 # Comparing a hashed password with a secret should compare successfully to the original secret
rspec ./spec/bcrypt/password_spec.rb:103 # Comparing a hashed password with a secret should compare unsuccessfully to anything besides original secret
rspec ./spec/bcrypt/password_spec.rb:121 # Validating a password hash should accept a valid password
```

Here is the full log from the run https://gist.github.com/agrare/3a20e6e3265909618bf853042070a159

**Comment by agrare** [comment]
And the previous commit:
```
$ git checkout e1320b0328b54a890be5f8ba7199fb4f59660fd7^
Previous HEAD position was e1320b0 unlock the gvl when calculating hashes / salts
HEAD is now at 2121626 Merge pull request #215 from jeremy/strdup-segfault
...
Finished in 5.71 seconds (files took 0.11859 seconds to load)
35 examples, 0 failures
```

**Comment by sadiqmmm** [comment]
# Using ruby 2.7.1p83 and Rails 6.0.3.2
# BCrypt::Errors::InvalidHash (invalid hash):

Started POST "/users/sign_in" for 183.83.68.119 at 2020-07-21 20:44:15 +0000
I, [2020-07-21T20:44:15.472841 #38305]  INFO -- : [efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] Processing by Devise::SessionsController#create as HTML
I, [2020-07-21T20:44:15.472902 #38305]  INFO -- : [efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3]   Parameters: {"authenticity_token"=>"rBDAT0uLfNQen9ZjR6CXCufG+aKSkPQ/dPo+rUiiANWt/y0TNCgm44GR3zk/w0X119rCPVkq1Jq+E+Nb3FAKpQ==", "user"=>{"email"=>"zzzzzzz@gmail.com", "password"=>"[FILTERED]", "remember_me"=>"1"}, "commit"=>"Log in"}
D, [2020-07-21T20:44:15.477102 #38305] DEBUG -- : [efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3]   User Load (1.1ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["email", "sadiqmmm@gmail.com"], ["LIMIT", 1]]
I, [2020-07-21T20:44:15.546170 #38305]  INFO -- : [efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] Completed 401 Unauthorized in 73ms (ActiveRecord: 1.1ms | Allocations: 1287)
I, [2020-07-21T20:44:15.547309 #38305]  INFO -- : [efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] Processing by Devise::SessionsController#new as HTML
I, [2020-07-21T20:44:15.547368 #38305]  INFO -- : [efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3]   Parameters: {"authenticity_token"=>"rBDAT0uLfNQen9ZjR6CXCufG+aKSkPQ/dPo+rUiiANWt/y0TNCgm44GR3zk/w0X119rCPVkq1Jq+E+Nb3FAKpQ==", "user"=>{"email"=>"sadiqmmm@gmail.com", "password"=>"[FILTERED]", "remember_me"=>"1"}, "commit"=>"Log in"}
I, [2020-07-21T20:44:15.617357 #38305]  INFO -- : [efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] Completed 500 Internal Server Error in 70ms (ActiveRecord: 0.0ms | Allocations: 966)
I, [2020-07-21T20:44:15.637135 #38305]  INFO -- : [efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] Sending event d968b04dd70e4ccf85ca23904ed75348 to Sentry
F, [2020-07-21T20:44:15.943358 #38305] FATAL -- : [efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3]   
[efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] BCrypt::Errors::InvalidHash (invalid hash):
[efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3]   
[efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] bcrypt (3.1.14) lib/bcrypt/password.rb:60:in `initialize'
[efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] bcrypt (3.1.14) lib/bcrypt/password.rb:46:in `new'
[efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] bcrypt (3.1.14) lib/bcrypt/password.rb:46:in `create'
[efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] devise (4.7.2) lib/devise/encryptor.rb:11:in `digest'
[efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] devise (4.7.2) lib/devise/models/database_authenticatable.rb:205:in `password_digest'
[efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] devise (4.7.2) lib/devise/models/database_authenticatable.rb:67:in `password='
[efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] activemodel (6.0.3.2) lib/active_model/attribute_assignment.rb:50:in `public_send'
[efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] activemodel (6.0.3.2) lib/active_model/attribute_assignment.rb:50:in `_assign_attribute'
[efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] activemodel (6.0.3.2) lib/active_model/attribute_assignment.rb:43:in `block in _assign_attributes'
[efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] activemodel (6.0.3.2) lib/active_model/attribute_assignment.rb:42:in `each'
[efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] activemodel (6.0.3.2) lib/active_model/attribute_assignment.rb:42:in `_assign_attributes'
[efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] activerecord (6.0.3.2) lib/active_record/attribute_assignment.rb:21:in `_assign_attributes'
[efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] activemodel (6.0.3.2) lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
[efa6e2dc-55cb-4b9f-bc08-dfd50eeb61e3] activerecord (6.0.3.2) lib/active_record/core.rb:325:in `initialize'

**Comment by tenderlove** [comment]
> Oh sorry wasn't clear enough, these specs actually fail not the MIQ specs

Got it.  Looks like everything works fine on macOS for some reason. 😩

I'll revert that patch and make a new release!

**Comment by agrare** [comment]
Awesome thanks!  And for the record I'm running Debian Testing/Bullseye

**Comment by tenderlove** [comment]
I was able to reproduce on Ubuntu (and the build is green there now).  Thanks for reporting this, and sorry about the breakage

**Comment by agrare** [comment]
Thanks for fixing this so quickly @tenderlove !

**Comment by agrare** [comment]
Updating the title to reflect that this actually was failing on at least ruby 2.6.3p62 also (cc @carbonin).  It seems more likely that it was broken on Linux

**Comment by sametimesolutions** [comment]
Is this something that needs to be backported into Jansa?
