### ISSUE TITLE
Maintenance of bcrypt-ruby (creation of ruby-crypto org?)

### ISSUE THREAD

**Issue by athix** [codahale/bcrypt-ruby#246]
Hi all,

Would there be any interest in moving the official location of the bcrypt-ruby library to an organization? This would help both with users finding the official repo more easily, and adding/removing maintainers over time. We could also consolidate other ruby wrappers for crypto libraries into this org (e.g. [technion/ruby-argon2](https://github.com/technion/ruby-argon2))

For example, we could have something like:

* [ruby-crypto/argon2](https://github.com/ruby-crypto/argon2)
* [ruby-crypto/bcrypt](https://github.com/ruby-crypto/bcrypt)
* Etc...

I've done this process before with moving Sorcery from [noamb/sorcery](https://github.com/noamb/sorcery) to [sorcery/sorcery](https://github.com/sorcery/sorcery), and would be willing to assist as much as needed for this process. I would also be willing to be a co-maintainer for bcrypt and argon2, if there's interest in having additional help.

For BCrypt, @codahale, would you be okay with moving the home of the codebase to a public organization? You would be made an owner of that org, and all existing maintainers (@tenderlove? @tjschuck?) admins.

For Argon2, @technion, how would you feel about this consolidation? Would you be interested in including Argon2 in the same org? Like @codahale, you would also be made an owner of this new org, and any maintainers (if you choose to add any) would be made admins.

Using `ruby-crypto` in particular would require the current user with that name (@ruby-crypto) to be willing to let us take the name, but it looks like their account has no public contributions, so it hopefully shouldn't be too much trouble.

**Comment by codahale** [comment]
I can’t speak for anyone else, but it’s been a solid decade since I wrote Ruby professionally, and I’d be more than happy to hand this off to anyone who’ll be responsible with it.

**Comment by tenderlove** [comment]
Moving the repo seems fine to me. I have to admit though, I hope that not much in this codebase changes as it's a security library, and it seems to be working very well as-is. 😅

**Comment by athix** [comment]
> I hope that not much in this codebase changes as it's a security library, and it seems to be working very well as-is.

Agreed, don't fix what ain't broke. :wink:

**Comment by technion** [comment]
From my view, I don't object to Argon2 moving to a corporation to ensure it's maintained in an ongoing manner. However, from what I'm seeing in the branch you're working on a significant refactoring with breaking changes. I'm very cautious about straying from @tenderlove 's point about changing a security library without a substantive reason.

**Comment by athix** [comment]
> However, from what I'm seeing in the branch you're working on a significant refactoring with breaking API changes, over a hundred lines of style changes, and a test suite thrown out and rewritten from scratch. I'm very cautious about straying from @tenderlove 's point about changing a security library without a substantive reason.

For those following along, this is the PR being mentioned: https://github.com/technion/ruby-argon2/pull/44

@technion I've reduced the styling changes and reverted the test suite back to minitest instead of rspec per your feedback. Please re-review when you have a chance. Not changing a security library without good reason is absolutely important, and I'm open to any/all constructive criticism on the changes made. Obviously I personally feel these changes are warranted, but I may be in the minority here. I'd be curious to see how others feel about the suggested changes.

**Comment by tjschuck** [comment]
> Moving the repo seems fine to me. I have to admit though, I hope that not much in this codebase changes as it's a security library, and it seems to be working very well as-is. 😅

For a similar reason, I would prefer just moving it to just a `bcrypt-ruby` org instead of a larger macro "ruby-crypto" org, just to minimize the surface area of maintenance and the scope of maintainers.

**Comment by athix** [comment]
> For a similar reason, I would prefer just moving it to just a bcrypt-ruby org instead of a larger macro "ruby-crypto" org, just to minimize the surface area of maintenance and the scope of maintainers.

@tjschuck 

The value I see behind using a macro "ruby-crypto" org is more for downstream developer's searchability than an expectation that all maintainers are responsible for all wrappers. Functionally maintainers _could_ be in multiple maintainer groups if they want, but the expectation would be that each wrapper's group of maintainers would work/triage issues only on their wrapper, and only have admin repo rights on that particular wrapper to reflect that.

This would make finding the various ruby crypto wrappers very straight-forward, letting downstream developers more easily choose which wrapper/algorithm is appropriate for their given use-case.

There would be the burden of a little extra setup with the permission groups initially, but like I said I'm willing to shoulder that transition cost if it would make finding things easier for others. Great documentation/SEO has made my life easier many times, so I'd like to give back if possible.

**Comment by tenderlove** [comment]
> For a similar reason, I would prefer just moving it to just a `bcrypt-ruby` org instead of a larger macro "ruby-crypto" org, just to minimize the surface area of maintenance and the scope of maintainers.

I think this would be good.

I understand the value of good documentation / SEO, but I also feel somewhat uneasy about moving this repo to an org where other folks I don't know may have access.  I guess only certain people can push the gem, but I just wanted to convey my feelings about a move. 😬

Moving to a `bcrypt-ruby` org would certainly help with SEO, but I guess maybe not help with "go here for all Ruby crypto libraries".

**Comment by tjschuck** [comment]
Let's do it.

@codahale Please transfer ownership of this repo to me (@tjschuck), and then I'll do everything else to get it all org'd up.  Thanks!

**Comment by athix** [comment]
> I understand the value of good documentation / SEO, but I also feel somewhat uneasy about moving this repo to an org where other folks I don't know may have access. I guess only certain people can push the gem, but I just wanted to convey my feelings about a move.

Fair concern. Speaking of which, are there any standards or recommendations when it comes to vetting new maintainers? (for open source in general) I feel like it's kind of the wild west in that regard atm, which is a bit unsettling considering how it can have far reaching consequences when it comes to commonly used libraries.

> Moving to a bcrypt-ruby org would certainly help with SEO, but I guess maybe not help with "go here for all Ruby crypto libraries".

Having a central place for ruby crypto libraries is only a nice to have, and it sounds like the security concerns out weigh the SEO value. Personally I would prefer having a nice URL and easy navigation to the other wrappers, but that's not my call to make. :man_shrugging: 

> Let's do it.
>
> @codahale Please transfer ownership of this repo to me (@tjschuck), and then I'll do everything else to get it all org'd up. Thanks!

Awesome! I'll close out this issue, sounds like we're going ahead with a bcrypt-ruby org for now.

**Comment by athix** [comment]
@tjschuck I'm sure you probably wouldn't, but just in-case: I would recommend not renaming this repo directly. Renaming the repo and destroying the existing URL would break a lot of external references (e.g. stackoverflow and blog articles). I would instead copy the repo over to the org, and then update this one to redirect users to the new location.

**Comment by codahale** [comment]
You’ve already got a `bcrypt-ruby` repo, @tjschuck, so I can’t transfer it to you right now.

**Comment by tjschuck** [comment]
@codahale I have now deleted my fork — sorry for the extra step!

**Comment by codahale** [comment]
No worries. Transfer request sent.

**Comment by codahale** [comment]
This seems as good a time as any to officially step entirely away from this project. Y’all have been wonderful stewards and I trust you to make wise decisions. It’s not every day I get to hand off a project, so from the bottom of my heart — thank you.

**Comment by tjschuck** [comment]
@codahale Right back at you — I'm grateful for all that you've done for this project, the community, and everything else.  Thank you!

Anyway, welcome to https://github.com/bcrypt-ruby/bcrypt-ruby, friends.
