### ISSUE TITLE
Update crypt_blowfish implementation from v1.1 to v1.2

### ISSUE THREAD

**Issue by tjschuck** [codahale/bcrypt-ruby#80]
[Version 1.2 was released in July of 2011](http://www.openwall.com/lists/announce/2011/07/17/1).

It looks like we're using version 1.1.

http://www.openwall.com/crypt/ for the new source.

Version 1.2 also supports the `$2y$` prefix, which fixes #39

**Comment by jeffdeville** [comment]
+1 It's causing compatibility issues with other systems that have moved to the newer algorithms.

**Comment by duane** [comment]
What's happening with this upgrade?

**Comment by reedloden** [comment]
Waiting for it to be merged...

**Comment by samcday** [comment]
Ping! @tjschuck are there any plans to get this released in a new version of the `bcrypt` gem?

**Comment by matfiz** [comment]
Any chances to get it merged? We're using bcrypt ruby in a system along with PHP lib, that generates pass with `$2y` prefix

**Comment by dissolve** [comment]
Based on atlassian's fork, I released a gem that has this fix in it as bcrypt4.  Does mean that it loses support for some versions of Ruby as a result (jruby)

**Comment by tjschuck** [comment]
Done in #182
